# Generated by Django 4.2.30 on 2026-07-09 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification_notificationcampaign_campaignrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('deposit', 'Nạp tiền'), ('withdraw', 'Rút tiền'), ('none', 'Không có')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='saving_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.savinggoal'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi tiêu'), ('saving', 'Tiết kiệm')], max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi tiêu'), ('saving', 'Tiết kiệm')], max_length=16),
        ),
    ]
